sudo: required
services:
    - docker

before_install:
    - docker build -t demisew/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true demisew/docker-react npm run test
language: generic